CREATE DATABASE AQI_DBB;
USE DATABASE AQI_DBB;

CREATE SCHEMA AQI_SCHEMA;
USE SCHEMA AQI_SCHEMA;
SHOW TABLES ;
DESCRIBE TABLE  DELHI_AQI_RAW;
SELECT * FROM DELHI_AQI_RAW LIMIT 10;
SELECT
    MIN(date) AS start_date,
    MAX(date) AS end_date
FROM DELHI_AQI_RAW;

// WHICH CITY HAS MORE RECORS  
SELECT CITY , COUNT(*) AS RECORDS FROM DELHI_AQI_RAW
GROUP BY CITY 
ORDER BY RECORDS DESC;

//TOTAL STATIONS (23)
SELECT COUNT(DISTINCT STATION) AS TOTAL_STATIONS FROM DELHI_AQI_RAW ;

//WHICH CITYS HAS MORE STATIONS (DELHI)
SELECT CITY,COUNT(DISTINCT STATION) AS STATIONS FROM DELHI_AQI_RAW
GROUP BY CITY;

//AVERAGE AQI 
SELECT AVG(AQI) FROM DELHI_AQI_RAW ;

// MAX AND MIN AQL
SELECT MIN(aqi) AS min_aqi,MAX(aqi) AS max_aqi,ROUND(AVG(aqi),3) AS avg_aqi
FROM DELHI_AQI_RAW;

//MOST POLLUTED CITY 
SELECT CITY , ROUND(AVG(AQI),2) AS AVG_AQI FROM DELHI_AQI_RAW
GROUP BY CITY 
ORDER BY AVG_AQI DESC;

//SEASON WISE POLLUTION
SELECT SEASON,ROUND(AVG(AQI),2) AS AVG_AQI FROM DELHI_AQI_RAW
GROUP BY SEASON
ORDER BY AVG_AQI DESC;

//WORST POLLUTION DAYS 
SELECT city, station, date, aqi FROM DELHI_AQI_RAW
ORDER BY aqi DESC
LIMIT 10;

// MONTHLY AQI TREND
SELECT YEAR, MONTH , ROUND(AVG(AQI)) AS AVG_AQI FROM DELHI_AQI_RAW
GROUP BY YEAR,MONTH ;

SELECT
    aqi_category,
    COUNT(*) AS days
FROM (
    SELECT
        CASE
            WHEN aqi <= 50 THEN 'Good'
            WHEN aqi <= 100 THEN 'Satisfactory'
            WHEN aqi <= 200 THEN 'Moderate'
            WHEN aqi <= 300 THEN 'Poor'
            WHEN aqi <= 400 THEN 'Very Poor'
            ELSE 'Severe'
        END AS aqi_category
    FROM DELHI_AQI_RAW
) t
GROUP BY aqi_category
ORDER BY days DESC;

//Correlation Analysis
SELECT 
    CORR(aqi, pm25) AS corr_pm25,
    CORR(aqi, pm10) AS corr_pm10
FROM DELHI_AQI_RAW;

//Weekday vs Weekend Pollution
select IS_WEEKEND ,
ROUND(AVG(AQI),2) AS AVG_AQI 
FROM DELHI_AQI_RAW
GROUP BY IS_WEEKEND ;

// pollution according to time of the day 
SELECT 
    hour,
    ROUND(AVG(aqi),2) AS avg_aqi
FROM DELHI_AQI_RAW
GROUP BY hour
ORDER BY hour;
// CORRELATION BETWEEN EACH PARTICLE 
SELECT 
    CORR(aqi, pm25) AS pm25_corr,
    CORR(aqi, pm10) AS pm10_corr,
    CORR(aqi, no2) AS no2_corr,
    CORR(aqi, co) AS co_corr
FROM DELHI_AQI_RAW;

// As wind speed increases, AQI decreases
select WIND_SPEED , ROUND(AVG(AQI),2) AS AVG_AQI,
FROM DELHI_AQI_RAW
GROUP BY WIND_SPEED
ORDER BY WIND_SPEED DESC;

SELECT CORR(aqi,WIND_SPEED) AS WIND FROM DELHI_AQI_RAW;

// RELATION BETWEEN TEMP AND POLLUTION
SELECT 
    ROUND(temperature) AS temp,
    ROUND(AVG(aqi),2) AS avg_aqi
FROM DELHI_AQI_RAW
GROUP BY temp
ORDER BY temp DESC;

// range of aqi and total days 
SELECT 
    FLOOR(aqi/50)*50 AS range_start,
    COUNT(*) AS total_days
FROM DELHI_AQI_RAW
GROUP BY range_start
ORDER BY range_start DESC;


